controller_manager:
  ros__parameters:
    update_rate: 30    
    #use_sim_time: true # lo comentamos por completo pues parece funcionar igual que poniendolo en false

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    base_frame_id: base_link
    odom_frame_id: odom

    use_stamped_vel: true  # false = acepta Twist, true = acepta TwistStamped
       
#    wheel_radius: 0.034
#    wheel_separation: 0.275
    wheel_radius: 0.045
    wheel_separation: 0.29

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']

    publish_rate: 50.0
    cmd_vel_timeout: 0.5
    


# no lo usamos por ahora, pero dejamos el ejemplo
#joint_broad:
#  ros__parameters: