controller_manager:
  ros__parameters:
    update_rate: 30
    #use_sim_time: false
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    base_frame_id: base_link
    use_stamped_vel: true  # false = acepta Twist, true = acepta TwistStamped
    cmd_vel_timeout: 0.5
    publish_rate: 50.0
   # open_loop: false
    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.35
    wheel_radius: 0.05


# no lo usamos por ahora, pero dejamos el ejemplo
#joint_broad:
#  ros__parameters: